version: "{build}"

image: Visual Studio 2017
platform:
  - x64

cache:
  - node_modules

branches:
  only:
    - /master|^v\d+\.\d+\.\d+$/

clone_depth: 10

install:
  # https://www.appveyor.com/docs/lang/nodejs-iojs/#installing-any-version-of-nodejs-or-iojs
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild 12) x64
  - npm install

build_script:
  - npm test
  - npm run prebuild-node
  - npm run prebuild-node-ia32
  - npm run prebuild-electron
  - npm run prebuild-electron-ia32
  - if defined APPVEYOR_REPO_TAG_NAME (npm run upload)

test: off
deploy: off
